"use client";

import { useState } from "react";

export default function RentalDetail({ params }: { params: Promise<{ id: string }> }) {
  const [requested, setRequested] = useState(false);

  return <main className="min-h-screen bg-gray-50 text-black"><header className="border-b bg-black px-6 py-5 text-white"><div className="mx-auto flex max-w-6xl items-center justify-between"><a href="/rent" className="text-sm text-gray-300 hover:text-white">← กลับไปดูของให้ยืม</a><a href="/" className="text-2xl font-black">P2P<span className="text-[#D4AF37]">.</span></a></div></header><div className="mx-auto grid max-w-6xl gap-8 px-6 py-12 lg:grid-cols-2"><div className="flex min-h-[420px] items-center justify-center rounded-2xl bg-gray-200 text-9xl">🎮</div><section className="rounded-2xl border bg-white p-8"><span className="text-sm font-bold text-[#B08D18]">เกม · อุบลราชธานี</span><h1 className="mt-3 text-4xl font-black">PlayStation 5</h1><p className="mt-3 text-gray-500">เครื่องพร้อมใช้งาน เหมาะสำหรับเล่นเกมหรือจัดกิจกรรม สามารถนัดรับในพื้นที่ได้</p><div className="my-8 grid grid-cols-2 gap-4"><div className="rounded-lg bg-gray-50 p-4"><p className="text-xs text-gray-500">ค่าเช่า</p><p className="mt-1 text-2xl font-black">฿300 <span className="text-sm font-normal">/ วัน</span></p></div><div className="rounded-lg bg-gray-50 p-4"><p className="text-xs text-gray-500">เงินประกัน</p><p className="mt-1 text-2xl font-black">฿3,000</p></div></div><div className="rounded-xl border p-5"><div className="flex items-center justify-between"><div><b>Game House</b><p className="mt-1 text-sm text-gray-500">🟢 ยืนยันตัวตนแล้ว · ⭐ 4.9</p></div><a href="/chat" className="rounded-lg border px-4 py-2 text-sm font-semibold hover:border-[#D4AF37]">💬 พูดคุย</a></div></div>{requested ? <div className="mt-5 rounded-xl border border-[#D4AF37] bg-[#fffaf0] p-5"><b>ส่งคำขอยืมแล้ว ✓</b><p className="mt-1 text-sm text-gray-600">รอผู้ให้ยืมตอบรับ คุณสามารถพูดคุยรายละเอียดผ่านแชตได้</p></div> : <button onClick={() => setRequested(true)} className="mt-6 w-full rounded-lg bg-[#D4AF37] px-5 py-4 font-black text-black hover:bg-[#e5c04a]">ขอยืมสินค้า</button>}<p className="mt-4 text-center text-xs text-gray-400">การส่งคำขอยืมจริงต้องตรวจสอบสถานะยืนยันตัวตนจาก server ก่อนเสมอ</p></section></div></main>;
}
