"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Button } from "@/components/ui/button";
import { FormMessage } from "@/components/ui/form-field";
import { BoltIcon, ClockIcon } from "@/components/ui/icons";
import { bookingFormSchema, type BookingFormInput } from "@/lib/forms/rental-actions";
import type { RentalPricingMode } from "@/lib/rental/bookings";

const money=new Intl.NumberFormat("th-TH",{maximumFractionDigits:2});const HOUR_MS=60*60*1000;const DAY_MS=24*HOUR_MS;
type UrgentRequest={id:string;status:string;rentalAmount:string;depositAmount:string;urgentReservationFeeAmount:string;reservationExpiresAt:string|null};
function toIso(value:string):string|null{if(!value)return null;const parsed=new Date(value);return Number.isNaN(parsed.getTime())?null:parsed.toISOString();}
function Countdown({expiresAt}:{expiresAt:string}){const[remaining,setRemaining]=useState(()=>Math.max(0,new Date(expiresAt).getTime()-Date.now()));useEffect(()=>{const timer=window.setInterval(()=>setRemaining(Math.max(0,new Date(expiresAt).getTime()-Date.now())),1000);return()=>window.clearInterval(timer);},[expiresAt]);const seconds=Math.ceil(remaining/1000);return <span>{remaining>0?`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,"0")}`:"หมดเวลา"}</span>;}

export function UrgentBookingForm({itemId,hourlyRate,dailyRate,minimumHours,urgentFeeRate}:{itemId:string;hourlyRate:string|null;dailyRate:string|null;minimumHours:number;urgentFeeRate:string}){
 const initialMode:RentalPricingMode=hourlyRate?"HOUR":"DAY";const[message,setMessage]=useState("");const[code,setCode]=useState("");const[created,setCreated]=useState<UrgentRequest|null>(null);
 const{register,handleSubmit,setValue,watch,formState:{errors,isSubmitting}}=useForm<BookingFormInput>({resolver:zodResolver(bookingFormSchema),defaultValues:{pricingMode:initialMode,startsAt:"",endsAt:""}});const mode=watch("pricingMode");const startsAt=watch("startsAt");const endsAt=watch("endsAt");
 const preview=useMemo(()=>{const start=toIso(startsAt);const end=toIso(endsAt);if(!start||!end)return null;const diff=new Date(end).getTime()-new Date(start).getTime();if(diff<=0)return null;const units=mode==="HOUR"?Math.ceil(diff/HOUR_MS):Math.ceil(diff/DAY_MS);const rate=Number(mode==="HOUR"?hourlyRate:dailyRate);if(!Number.isFinite(rate)||rate<=0)return null;const rental=rate*units;return{units,rental,urgentFee:rental*Number(urgentFeeRate),valid:mode!=="HOUR"||units>=minimumHours};},[startsAt,endsAt,mode,hourlyRate,dailyRate,minimumHours,urgentFeeRate]);
 const reserve=handleSubmit(async(values)=>{const start=toIso(values.startsAt);const end=toIso(values.endsAt);if(!start||!end||!preview||!preview.valid){setMessage(values.pricingMode==="HOUR"&&preview&&!preview.valid?`ต้องยืมอย่างน้อย ${minimumHours} ชั่วโมง`:"กรุณาเลือกช่วงเวลาให้ถูกต้อง");return;}setMessage("");setCode("");try{const response=await fetch("/api/rental-requests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({itemId,pricingMode:values.pricingMode,startsAt:start,endsAt:end,isUrgent:true})});const payload=await response.json() as {ok:boolean;request?:UrgentRequest;code?:string;message?:string;fieldErrors?:Record<string,string>};if(!response.ok||!payload.ok||!payload.request){setCode(payload.code||"");setMessage((payload.fieldErrors&&Object.values(payload.fieldErrors)[0])||payload.message||"จองยืมด่วนไม่สำเร็จ");return;}setCreated(payload.request);}catch{setMessage("เชื่อมต่อระบบยืมด่วนไม่สำเร็จ กรุณาลองใหม่");}});
 if(created)return <section className="mt-5 rounded-2xl border border-[var(--gold-line)] bg-[var(--gold-soft)] p-5"><div className="flex items-start justify-between gap-3"><div><p className="inline-flex items-center gap-2 font-black"><BoltIcon size={17}/>ล็อกยืมด่วนสำเร็จ</p><p className="mt-1 text-xs text-[var(--muted-strong)]">สถานะ {created.status} · ยังไม่ถือว่าชำระแล้วจน payment สำเร็จ</p></div>{created.reservationExpiresAt&&<span className="inline-flex items-center gap-1.5 rounded-full bg-[var(--ink)] px-3 py-1 text-xs font-black text-white"><ClockIcon size={13}/><Countdown expiresAt={created.reservationExpiresAt}/></span>}</div><div className="mt-4 space-y-2 rounded-xl bg-white/70 p-4 text-sm"><div className="flex justify-between"><span>ค่าเช่า</span><b>฿{money.format(Number(created.rentalAmount))}</b></div><div className="flex justify-between"><span>เงินประกัน</span><b>฿{money.format(Number(created.depositAmount))}</b></div><div className="flex justify-between border-t border-[var(--line)] pt-2"><span>ค่าจองด่วนผ่านแพลตฟอร์ม</span><b>฿{money.format(Number(created.urgentReservationFeeAmount))}</b></div></div><Link href={`/checkout/${created.id}`} className="mt-4 inline-flex min-h-11 items-center rounded-xl bg-[var(--ink)] px-4 text-sm font-black text-white">ไปชำระเงิน</Link></section>;
 return <form onSubmit={reserve} className="mt-5 rounded-2xl border border-[var(--gold-line)] bg-[var(--gold-soft)] p-5" noValidate><div className="flex items-center justify-between gap-3"><div><p className="inline-flex items-center gap-2 font-black"><BoltIcon size={17}/>ยืมด่วน</p><p className="mt-1 text-xs text-[var(--muted-strong)]">ล็อกช่วงเวลาสำหรับคนแรกที่จองสำเร็จ</p></div><span className="rounded-full bg-[var(--gold)] px-3 py-1 text-xs font-black">ค่าจอง {Number(urgentFeeRate)*100}%</span></div><input type="hidden" {...register("pricingMode")}/><div className="mt-4 grid grid-cols-2 gap-2">{hourlyRate&&<button type="button" onClick={()=>setValue("pricingMode","HOUR")} className={`min-h-10 rounded-xl border px-3 text-xs font-black ${mode==="HOUR"?"border-[var(--ink)] bg-[var(--ink)] text-white":"border-[var(--gold-line)] bg-white"}`}>รายชั่วโมง</button>}{dailyRate&&<button type="button" onClick={()=>setValue("pricingMode","DAY")} className={`min-h-10 rounded-xl border px-3 text-xs font-black ${mode==="DAY"?"border-[var(--ink)] bg-[var(--ink)] text-white":"border-[var(--gold-line)] bg-white"}`}>รายวัน</button>}</div><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold">เริ่มยืม<input type="datetime-local" {...register("startsAt")} className="bb-input mt-1 min-h-11 bg-white text-sm"/><FormMessage>{errors.startsAt?.message}</FormMessage></label><label className="text-xs font-bold">คืนของ<input type="datetime-local" {...register("endsAt")} className="bb-input mt-1 min-h-11 bg-white text-sm"/><FormMessage>{errors.endsAt?.message}</FormMessage></label></div>{preview&&<div className="mt-3 rounded-xl bg-white/70 p-3 text-xs"><div className="flex justify-between"><span>ค่าเช่าโดยประมาณ</span><b>฿{money.format(preview.rental)}</b></div><div className="mt-1 flex justify-between"><span>ค่าจองยืมด่วน</span><b>฿{money.format(preview.urgentFee)}</b></div>{!preview.valid&&<p className="mt-2 font-bold text-red-600">ขั้นต่ำ {minimumHours} ชั่วโมง</p>}</div>}{message&&<p role="alert" className="mt-3 rounded-xl bg-red-50 p-3 text-xs font-semibold text-red-700">{message}{code==="UNAUTHENTICATED"&&<Link href={`/login?next=${encodeURIComponent(`/rent/${itemId}`)}`} className="ml-1 underline">เข้าสู่ระบบ</Link>}{code==="VERIFICATION_REQUIRED"&&<Link href="/verification" className="ml-1 underline">ยืนยันตัวตน</Link>}</p>}<Button type="submit" disabled={isSubmitting||!preview||!preview.valid} variant="gold" className="mt-4 w-full"><BoltIcon size={16}/>{isSubmitting?"กำลังล็อกช่วงเวลา...":"จองยืมด่วน"}</Button></form>;
}
