"use client";

import { useState } from "react";

export default function LendPage() {
  const [submitted, setSubmitted] = useState(false);
  const [form, setForm] = useState({ title: "", category: "", price: "", deposit: "", description: "" });

  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));

  return <main className="min-h-screen bg-gray-50 text-black"><header className="border-b bg-black px-6 py-5 text-white"><div className="mx-auto flex max-w-5xl items-center justify-between"><a href="/" className="text-2xl font-black">P2P<span className="text-[#D4AF37]">.</span></a><a href="/rent" className="text-sm text-gray-300 hover:text-white">ดูของให้ยืม</a></div></header><div className="mx-auto max-w-3xl px-6 py-12"><p className="text-sm font-bold tracking-[3px] text-[#B08D18]">LEND YOUR ITEM</p><h1 className="mt-2 text-4xl font-black">ลงของให้คนอื่นยืม</h1><p className="mt-3 text-gray-500">สร้างประกาศ กำหนดราคาและเงินประกัน แล้วรอคำขอจากผู้ยืม</p><div className="mt-8 rounded-2xl border bg-white p-7 shadow-sm"><div className="mb-6 rounded-xl bg-gray-50 p-4 text-sm">🔐 การลงของให้ยืมต้องผ่านการยืนยันตัวตนก่อน ระบบจริงจะตรวจสถานะ VERIFIED จาก server</div>{submitted ? <div className="rounded-xl border border-[#D4AF37] bg-[#fffaf0] p-6"><h2 className="text-xl font-bold">ส่งประกาศแล้ว ✓</h2><p className="mt-2 text-gray-600">รายการของคุณอยู่ในสถานะรอตรวจสอบ/เผยแพร่</p><a href="/rent" className="mt-5 inline-block rounded-lg bg-black px-5 py-3 font-bold text-white">กลับไปดูของให้ยืม</a></div> : <div className="grid gap-5"><label className="text-sm font-bold">ชื่อสิ่งของ<input value={form.title} onChange={(e) => update("title", e.target.value)} placeholder="เช่น กล้อง Sony A7III" className="mt-2 w-full rounded-lg border px-4 py-3 font-normal" /></label><label className="text-sm font-bold">หมวดหมู่<select value={form.category} onChange={(e) => update("category", e.target.value)} className="mt-2 w-full rounded-lg border bg-white px-4 py-3 font-normal"><option value="">เลือกหมวดหมู่</option><option>อิเล็กทรอนิกส์</option><option>เกม</option><option>แคมป์ปิ้ง</option><option>เครื่องมือ</option><option>กีฬา</option><option>อื่น ๆ</option></select></label><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-bold">ค่าเช่า / วัน<input type="number" value={form.price} onChange={(e) => update("price", e.target.value)} placeholder="300" className="mt-2 w-full rounded-lg border px-4 py-3 font-normal" /></label><label className="text-sm font-bold">เงินประกัน<input type="number" value={form.deposit} onChange={(e) => update("deposit", e.target.value)} placeholder="3000" className="mt-2 w-full rounded-lg border px-4 py-3 font-normal" /></label></div><label className="text-sm font-bold">รายละเอียด<textarea value={form.description} onChange={(e) => update("description", e.target.value)} rows={5} placeholder="อธิบายสภาพของ อุปกรณ์ที่ให้มาด้วย เงื่อนไขการรับคืน..." className="mt-2 w-full rounded-lg border px-4 py-3 font-normal" /></label><button onClick={() => setSubmitted(true)} disabled={!form.title || !form.category || !form.price} className="rounded-lg bg-[#D4AF37] px-5 py-4 font-black disabled:cursor-not-allowed disabled:opacity-40">สร้างประกาศให้ยืม</button></div>}</div></div></main>;
}
