"use client";

import { useState } from "react";
import { BoltIcon } from "@/components/ui/icons";
import { StatusPill } from "@/components/ui/primitives";
import { URGENT_RESERVATION_FEE_PERCENT } from "@/lib/rental/fees";

type Listing={id:string;title:string;status:string;urgentEnabled:boolean;urgentReservationFeeRate:string};
export default function UrgentListingManager({initialItems}:{initialItems:Listing[]}){const[items,setItems]=useState(initialItems);const[busyId,setBusyId]=useState("");const[message,setMessage]=useState("");const toggle=async(item:Listing)=>{setBusyId(item.id);setMessage("");try{const response=await fetch(`/api/rental-items/${item.id}/urgent`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({enabled:!item.urgentEnabled})});const payload=await response.json();if(!response.ok||!payload.ok)throw new Error(payload.message||"อัปเดตโหมดยืมด่วนไม่สำเร็จ");setItems((current)=>current.map((entry)=>entry.id===item.id?{...entry,urgentEnabled:payload.item.urgentEnabled,urgentReservationFeeRate:payload.item.urgentReservationFeeRate}:entry));}catch(error){setMessage(error instanceof Error?error.message:"อัปเดตโหมดยืมด่วนไม่สำเร็จ");}finally{setBusyId("");}};return <section className="mx-auto max-w-7xl px-4 pb-12 sm:px-6 lg:px-8"><div className="rounded-[26px] border border-[var(--gold-line)] bg-[var(--gold-soft)] p-5 sm:p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2"><BoltIcon size={18} className="text-[var(--gold-strong)]"/><p className="bb-label">Urgent availability</p></div><h2 className="mt-2 text-xl font-black">เปิด / ปิด “ยืมด่วน” ได้ตลอด</h2><p className="mt-1 text-sm text-[var(--muted-strong)]">ปิดเมื่อไม่สะดวกส่งมอบ และเปิดอีกครั้งเมื่อพร้อมโดยไม่สร้างประกาศใหม่</p></div><span className="text-[10px] font-bold text-[var(--gold-strong)]">ค่าจองผ่านแพลตฟอร์ม {URGENT_RESERVATION_FEE_PERCENT}% · กำหนดโดยระบบ</span></div>{message&&<p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{message}</p>}<div className="mt-5 grid gap-3 md:grid-cols-2">{items.map((item)=><article key={item.id} className="flex items-center justify-between gap-4 rounded-2xl border border-[var(--line)] bg-white p-4"><div className="min-w-0"><p className="truncate font-black">{item.title}</p><div className="mt-2 flex items-center gap-2"><StatusPill>{item.status}</StatusPill><span className="text-[10px] font-semibold text-[var(--muted)]">ค่าจอง {URGENT_RESERVATION_FEE_PERCENT}%</span></div></div><button type="button" disabled={busyId===item.id||item.status!=="ACTIVE"} onClick={()=>void toggle(item)} className={`inline-flex min-h-10 shrink-0 items-center gap-1.5 rounded-full px-4 text-xs font-black disabled:opacity-40 ${item.urgentEnabled?"bg-[var(--ink)] text-white":"border border-[var(--line)] bg-white"}`}><BoltIcon size={13}/>{busyId===item.id?"กำลังบันทึก...":item.urgentEnabled?"เปิดอยู่":"ปิดอยู่"}</button></article>)}{!items.length&&<p className="text-sm text-[var(--muted)]">ยังไม่มีประกาศสำหรับตั้งค่า</p>}</div></div></section>;
}
