"use client";

import { useState } from "react";

const seed = [
  { id: 1, name: "Game House", message: "สวัสดีครับ สอบถามรายละเอียดการยืมได้เลยครับ", time: "16:24", mine: false },
  { id: 2, name: "คุณ", message: "ขอสอบถามเรื่องอุปกรณ์และวันรับของครับ", time: "16:25", mine: true },
];

export default function ChatPage() {
  const [messages, setMessages] = useState(seed);
  const [text, setText] = useState("");
  const send = () => { if (!text.trim()) return; setMessages([...messages, { id: Date.now(), name: "คุณ", message: text.trim(), time: new Date().toLocaleTimeString("th-TH", { hour: "2-digit", minute: "2-digit" }), mine: true }]); setText(""); };
  return <main className="min-h-screen bg-[#f7f7f5] text-neutral-900"><header className="border-b border-neutral-200 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-5"><a href="/" className="text-2xl font-black tracking-tight">P2P<span className="text-[#c9a227]">.</span></a><div className="flex gap-3"><a href="/dashboard" className="rounded-full border px-4 py-2 text-sm font-semibold hover:border-[#c9a227]">Dashboard</a><a href="/rent" className="rounded-full bg-neutral-900 px-4 py-2 text-sm font-semibold text-white">ยืมของ</a></div></div></header><div className="mx-auto grid max-w-6xl gap-6 px-6 py-8 lg:grid-cols-[300px_1fr]"><aside className="rounded-3xl border border-neutral-200 bg-white p-4"><p className="px-3 py-3 text-xs font-black uppercase tracking-[3px] text-[#a58316]">Messages</p><div className="rounded-2xl bg-[#faf7ed] p-4 ring-1 ring-[#e7d9a8]"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-full bg-neutral-900 text-lg text-white">🎮</div><div><b>Game House</b><p className="mt-1 text-xs text-neutral-500">PlayStation 5 · R-0001</p></div></div><p className="mt-3 truncate text-sm text-neutral-600">สอบถามรายละเอียดการยืมได้เลยครับ</p></div></aside><section className="flex min-h-[650px] flex-col overflow-hidden rounded-3xl border border-neutral-200 bg-white shadow-sm"><div className="border-b border-neutral-200 px-6 py-5"><div className="flex items-center justify-between"><div><h1 className="text-xl font-black">Game House</h1><p className="mt-1 text-sm text-neutral-500">PlayStation 5 · Rental R-0001</p></div><span className="rounded-full bg-green-50 px-3 py-1 text-xs font-bold text-green-700">● ออนไลน์</span></div></div><div className="flex-1 space-y-4 overflow-y-auto bg-[#fcfcfb] p-6">{messages.map((m) => <div key={m.id} className={`flex ${m.mine ? "justify-end" : "justify-start"}`}><div className={`max-w-[75%] rounded-2xl px-4 py-3 ${m.mine ? "rounded-br-md bg-neutral-900 text-white" : "rounded-bl-md border border-neutral-200 bg-white"}`}><p className="text-sm leading-6">{m.message}</p><p className="mt-1 text-[11px] text-neutral-400">{m.time}</p></div></div>)}</div><div className="border-t border-neutral-200 bg-white p-4"><div className="flex gap-3"><input value={text} onChange={(e) => setText(e.target.value)} onKeyDown={(e) => e.key === "Enter" && send()} placeholder="พิมพ์ข้อความ..." className="flex-1 rounded-2xl border border-neutral-200 bg-neutral-50 px-4 py-3 outline-none transition focus:border-[#c9a227] focus:ring-2 focus:ring-[#c9a227]/20" /><button onClick={send} className="rounded-2xl bg-[#c9a227] px-6 py-3 font-black text-white hover:bg-[#b28d1e]">ส่ง</button></div><p className="mt-2 px-1 text-xs text-neutral-400">Prototype: ข้อความจะเชื่อมกับ NoSQL จริงในขั้น Database</p></div></section></div></main>;
}
